DROP TABLE IF EXISTS project_worker;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS worker;

CREATE TABLE IF NOT EXISTS worker (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INTEGER CHECK (SALARY >= 100 AND SALARY <= 100000)
    );

CREATE TABLE IF NOT EXISTS client (
       ID IDENTITY PRIMARY KEY,
       NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
    );

CREATE TABLE IF NOT EXISTS project (
       ID IDENTITY PRIMARY KEY,
       CLIENT_ID INTEGER,
        START_DATE DATE,
        FINISH_DATE DATE,
        FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
    );

CREATE TABLE IF NOT EXISTS project_worker (
        PROJECT_ID INTEGER,
         WORKER_ID INTEGER,
         PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
    );